# Test script for integration of Jenkins and Ansible.

- hosts: localhost

  vars:
     region: us-west-1
     jenkins_security_group_name: Jenkins-Server-sg
     instance_type: t2.micro
     base_image_name: ami-056ee704806822732
     number_of_instances_to_create: 1
     python_version: '3.7.4'

  tasks:
    - name: Create a suitable set of firewall rules
      ec2_group:
         name: "{{ jenkins_security_group_name }}"
         description: Specific rules for a Jenkins Instance
         region: "{{ region }}"
         rules_egress:
            - proto: tcp
              from_port: 0
              to_port: 65535
              cidr_ip: 0.0.0.0/0
         rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0

            - proto: tcp
              from_port: 8080
              to_port: 8080
              cidr_ip: 0.0.0.0/0

    - name: Start up an EC2 Temporary Instance
      ec2:
        key_name: vijaysmu-keypair
        group: "{{ jenkins_security_group_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ base_image_name }}"
        wait: yes
        region: "{{ region }}"
        exact_count: "{{ number_of_instances_to_create }}"
        instance_tags:
          Name: Dummy_Test
        count_tag:
          Name: Dummy_Test
      register: ec2

    - name: Gather the new ip addresses
      add_host: 
        groups=new_ec2_instances 
        hostname="{{ item.public_ip }}"
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH Server to start responding
      wait_for:
              port: 22
              host: "{{ item.public_ip }}"
              state: started
      with_items: "{{ ec2.instances }}"

- hosts: new_ec2_instances, tag_Name_Dummy_Test

  tasks:

    - name: upgrade all packages
      yum: name=* state=latest
      become: yes

    - name: Hello World, is this Working?
      debug: msg="Hello? Is this working?"
    
    - name: Check if Python3 is installed
      command: python3 -V
      ignore_errors: True
      register: python3_installed
      changed_when: False

    - name: Print Python version
      debug:
        var: python3_installed.stdout

    - name: Download and untar Python3 source files
      unarchive:
        src: 'https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tar.xz'
        dest: /usr/src
        remote_src: yes
      become: yes
      when: python3_installed.stdout is not defined

    - name: Configure Python
      command: ./configure --enable-optimizations
      args:
        chdir: '/usr/src/Python-{{ python_version }}'
      become: yes
      when: python3_installed.stdout is not defined

    - name: Install Python
      make:
        chdir: '/usr/src/Python-{{ python_version }}'
        target: altinstall
      become: yes
      when: python3_installed.stdout is not defined

    - name: install the latest version of python-boto
      yum:
          name: python-boto
          state: latest
      become: yes
      
    - name: install the latest version of python-boto3
      yum:
        name: python-boto3
        state: latest
      become: yes  


  tasks:

    - name: All working so destroy the temporary instance
      ec2:
        key_name: vijaysmu-keypair
        group: jenkins2_server_security_groups
        instance_type: notneeded
        image: notneeded
        wait: yes
        region: "{{ region }}"
        exact_count: 0
        instance_tags:
          Name: Dummy_Test
        count_tag:
          Name: Dummy_Test
